name: Lint

on:
  push:

jobs:
  build:
      name: Lint and Test
      runs-on: ubuntu-latest

      steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:
            fetch-depth: 2

        - name: Setup Node.js environment
          uses: actions/setup-node@v2
          with:
            node-version: 18
            cache: 'npm'

        - name: Install dependencies
          run: npm ci

        - name: Lint
          run: npm run lint
